[env:esp32p4]
platform = espressif32
board = esp32p4-devkitc
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = custom_partitions.csv
board_upload.flash_size = 16MB
